const products = [
  { name: "Face Mask", img: "images/jart.jpg", link: "https://amzn.to/4lpEyRF",
    tags: ["skin care","women","girls","makeup","skincare","korean"] },
  { name: "Collagen Mask", img: "images/mask.jpg", link: "https://amzn.to/4fDm3b3",
    tags: ["skin care","women","makeup","skincare","korean"] },
  { name: "Collagen Mask", img: "images/volu.jpg", link: "https://amzn.to/45yAGrz",
    tags: ["skin care","women","makeup","skincare","korean"] },
  { name: "Lip Stain", img: "images/lipptik.jpg", link: "https://amzn.to/3V1N5PX",
    tags: ["women","makeup","skincare","lip","bridesmaid","bridesmaids","tiktok"] },
  { name: "Dior Lip Oil Dupe", img: "images/elf.jpg", link: "https://amzn.to/4mkFxnF",
    tags: ["women","makeup","skincare","lip","bridesmaid","bridesmaids","tiktok"] },
  { name: "Selfie Light", img: "images/light.jpg", link: "https://amzn.to/4loRmYx",
    tags: ["women","girls","makeup","tiktok","cool"] },
  { name: "Celeb Fave Bronzer", img: "images/phys.jpg", link: "https://amzn.to/4fA9bCB",
    tags: ["women","makeup","bronzer","bridesmaid","bridesmaids","tiktok"] },
  { name: "Dyson Dupe", img: "images/dyson.jpg", link: "https://amzn.to/4mITkE8",
    tags: ["women","girls","makeup","hair","tiktok"] },
  { name: "Pimple Patches", img: "images/pimple.jpg", link: "https://amzn.to/3Uu8qRW",
    tags: ["women","girls","teen","skincare","tiktok"] },
  { name: "Stanley Snack Tray", img: "images/stanley.jpg", link: "https://amzn.to/4fLIACU",
    tags: ["women","girls","teen","tiktok","cool"] },
  { name: "Airplane Phone Mount", img: "images/phone.jpg", link: "https://amzn.to/46YgCl0",
    tags: ["men","tiktok","cool"] },
  { name: "Easy Pasta Strainer", img: "images/pasta.jpg", link: "https://amzn.to/45PAKEF",
    tags: ["women","men","tiktok","cool"] },
  { name: "Jellyfish Lamp", img: "images/jelly.jpg", link: "https://amzn.to/4lvubfo",
    tags: ["boys","girls","cool","tiktok"] },
  { name: "Cloud Slippers", img: "images/cloud.jpg", link: "https://amzn.to/45RW7W0",
    tags: ["girls","women","tiktok","fashion"] },
  { name: "Speakers", img: "images/speakers.jpg", link: "https://amzn.to/46RBWsi",
    tags: ["boys","men","tiktok","cool"] },

  { name: "Tna Socks Dupe", img: "images/dupe1.jpg", link: "https://amzn.to/3UadoDe",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Contour Esteem Bodysuit Dupe", img: "images/dupe2.jpg", link: "https://amzn.to/3JewWnC",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Squareneck Longsleeve Contour Bodysuit Dupe", img: "images/dupe3.jpg", link: "https://amzn.to/41gFGjm",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Contour Tshirt Crew Dupe", img: "images/dupe4.jpg", link: "https://amzn.to/45wKd3D",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Contour Boatneck Top Dupe", img: "images/dupe5.jpg", link: "https://amzn.to/45wKd3D",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Superpuff Vest Shorty Dupe", img: "images/dupe6.jpg", link: "https://amzn.to/46Giz5u",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Superpuff Long Dupe", img: "images/dupe7.jpg", link: "https://amzn.to/4fgcPRU",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Zip Up Dupe", img: "images/dupe8.jpg", link: "https://amzn.to/4miaF6O",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Cheeky Hi Rise Leggings Dupe", img: "images/dupe9.jpg", link: "https://amzn.to/3IZvvJK",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Cheeky Flare Dupe", img: "images/dupe10.jpg", link: "https://amzn.to/45dbQxm",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Essential Skort Dupe", img: "images/dupe11.jpg", link: "https://amzn.to/4m8z5zV",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Romper Dupe", img: "images/dupe12.jpg", link: "https://amzn.to/45dbTcw",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Tna Golden Butter Biker Shorts Dupe", img: "images/dupe13.jpg", link: "https://amzn.to/40NZfPW",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Sweatfleece Hoodie Dupe", img: "images/dupe14.jpg", link: "https://amzn.to/3U6vV3o",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Sweatfleece Cinched Sweatpant Dupe", img: "images/dupe15.jpg", link: "https://amzn.to/3UJuYOC",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Sweatfleece Cargo Sweatpant Dupe", img: "images/dupe16.jpg", link: "https://amzn.to/4moE8vI",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Sweatfleece Straight Sweatpant Dupe", img: "images/dupe17.jpg", link: "https://amzn.to/45wyT7A",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Align Leggings Dupe", img: "images/dupe18.jpg", link: "https://amzn.to/45bGcjS",
    tags: ["women","girls","dupe","fashion","aritzia dupe"] },
  { name: "Nulu Flare Dupe", img: "images/dupe19.jpg", link: "https://amzn.to/4lWG5j8",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Track Highrise Shorts Dupe", img: "images/dupe20.jpg", link: "https://amzn.to/41pMew1",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Biker Shorts Dupe", img: "images/dupe21.jpg", link: "https://amzn.to/3IZL5F8",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Zip With Hood Dupe", img: "images/dupe22.jpg", link: "https://amzn.to/40PJLee",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Halfzip Dupe", img: "images/dupe23.jpg", link: "https://amzn.to/452sEs4",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Joggers Dupe", img: "images/dupe24.jpg", link: "https://amzn.to/4oql9TB",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Scooba Halfzip Dupe", img: "images/dupe25.jpg", link: "https://amzn.to/4fnT6jt",
    tags: ["women","girls","dupe","fashion","lululemon dupe"] },
  { name: "Bodysuit Dupe", img: "images/dupe26.jpg", link: "https://amzn.to/4l62zNt",
    tags: ["women","girls","dupe","fashion","skims dupe"] },
  { name: "Tank Top Dupe", img: "images/dupe27.jpg", link: "https://amzn.to/3IYV1Pg",
    tags: ["women","girls","dupe","fashion","tank air dupe"] },
];
